export const GET_LIST_QUESTION = "GET_LIST_QUESTION";

export const GET_LIST_QUESTION_SUCCESS = "GET_LIST_QUESTION_SUCCESS";

export const GET_LIST_QUESTION_FAILED = "GET_LIST_QUESTION_FAILED";

export const ADD_SELECT_QUESTION = "ADD_SELECT_QUESTION";

export const RESET_SELECT_QUESTION = "RESET_SELECT_QUESTION";
