/**
 * action get list QUESTIONS
 */

export const GET_LIST_QUESTION = "GET_LIST_QUESTION";

export const GET_LIST_QUESTION_SUCCESS = "GET_LIST_QUESTION_SUCCESS";

export const GET_LIST_QUESTION_FAILED = "GET_LIST_QUESTION_FAILED";
